services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - /Users/talmage/.config/gcloud:/root/.config/gcloud:ro
